apiVersion: v1
kind: Service
metadata:
  name: mysqlsrv
  labels:
    name: mysqlsrv
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3306
    targetPort: 3306
  selector:
    name: mysql-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-db-deploy
  labels:
    name: mysql-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mysql-db
    spec:
      containers:
      - image: docker.io/mysql
        name: mysql-cntr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort:  3306
          name: mysql-db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: azure
      volumes:
        - name: azure
          azureFile:
             secretName: azure-secret
             shareName: webpocmysqlshare
